name: babylon-server

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Download API spec artifact with curl
      run: |
        curl -L -o "$ARTIFACT_NAME.zip" \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.babylon-api-pat }}" \
          "https://github.com/ajponte/babylon_api_spec/actions/runs/$RUN_ID/artifacts/3988763991"

        unzip -o -j "$ARTIFACT_NAME.zip" -d ./api-specs
        
        rm "$ARTIFACT_NAME.zip"

      env:
        REPO: ajponte/babylon_api_spec
        RUN_ID: 17652643510
        ARTIFACT_NAME: api-spec-17652643510
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        pip install poetry 
        # Install poetry dependencies only.
        poetry install
    - name: Pylint checks
      run: |
        tox -e lint
    - name: Formatting checks
      run: |
        tox -e format
    - name: Pytest
      run: |
        tox -e pytest
