name: babylon-server

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Download API spec artifact with gh cli
      run: |
        gh run download $RUN_ID --repo $REPO --dir ./api-specs --name "$ARTIFACT_NAME"
      env:
        GH_TOKEN: ${{ secrets.babylon-api-pat }}
        REPO: ajponte/babylon_api_spec
        RUN_ID: 17652643510
        ARTIFACT_NAME: api-spec-17652643510
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        pip install poetry 
        # Install poetry dependencies only.
        poetry install
    - name: Pylint checks
      run: |
        tox -e lint
    - name: Formatting checks
      run: |
        tox -e format
    - name: Pytest
      run: |
        tox -e pytest
